name: bp_logger_plus
description: Simple blood pressure monitor with charts, export and reminders
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.66.2
  share_plus: ^10.0.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
