name: bp_logger
description: Offline BP diary with charts, reminders, CSV/PDF export
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  fl_chart: ^0.68.0
  share_plus: ^10.0.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.3
  flutter_native_timezone: ^2.0.0
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
