name: bp_logger
description: Мониторинг давления
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.3
  fl_chart: ^0.66.2

flutter:
  uses-material-design: true
