name: bp_logger
description: Simple BP logger app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0

  # storage / share
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2

  # notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
